[manager]
cwd = { fg = "#21c7a8" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e3d18a", bold = true, italic = true, underline = true }
find_position = { fg = "#ff5874", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#21c7a8", bg = "#21c7a8" }
marker_cut      = { fg = "#ff5874", bg = "#ff5874" }
marker_marked   = { fg = "#82aaff", bg = "#82aaff" }
marker_selected = { fg = "#e3d18a", bg = "#e3d18a" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#1d3b53", bg = "#21c7a8" }
count_cut      = { fg = "#1d3b53", bg = "#ff5874" }
count_selected = { fg = "#1d3b53", bg = "#e3d18a" }

# Border
border_symbol = "â”‚"
border_style  = { fg = "#1d3b53" }


# : Status {{{

[status]
separator_open  = "î‚¶"
separator_close = "î‚´"
separator_style = { fg = "#1d3b53", bg = "#1d3b53" }

# Mode
mode_normal = { fg = "#1d3b53", bg = "#82aaff", bold = true }
mode_select = { fg = "#1d3b53", bg = "#e3d18a", bold = true }
mode_unset  = { fg = "#1d3b53", bg = "#ff5874", bold = true }

# Progress
progress_label  = { fg = "#d6deeb", bold = true }
progress_normal = { fg = "#82aaff", bg = "#1d3b53" }
progress_error  = { fg = "#fc514e", bg = "#1d3b53" }

# Permissions
permissions_t = { fg = "#a1cd5e" }
permissions_r = { fg = "#ecc48d" }
permissions_w = { fg = "#fc514e" }
permissions_x = { fg = "#7fdbca" }
permissions_s = { fg = "#7c8f8f" }

[pick]
border   = { fg = "#1d3b53" }
active   = { fg = "#c792ea", bold = true }
inactive = {}


[input]
border   = { fg = "#1d3b53" }
title    = {}
value    = {}
selected = { reversed = true }


[confirm]
border     = { fg = "#1d3b53" }
title      = { fg = "#c792ea" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ " [Y]es ", " (N)o " ]


[completion]
border   = { fg = "#1d3b53" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = "ï…›"
icon_folder  = "ï„•"
icon_command = "ï’‰"

[tasks]
border  = { fg = "#1d3b53" }
title   = {}
hovered = { fg = "#c792ea", underline = true }


[which]
cols            = 3
mask            = { bg = "#1d3b53" }
cand            = { fg = "#7fdbca" }
rest            = { fg = "#d6deeb" }
desc            = { fg = "#c792ea" }
separator       = " îªœ "
separator_style = { fg = "#7c8f8f" }


[help]
on      = { fg = "#7fdbca" }
run     = { fg = "#c792ea" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#1d3b53", bg = "#bdc1c6" }


[notify]
title_info  = { fg = "#a1cd5e" }
title_warn  = { fg = "#e3d18a" }
title_error = { fg = "#fc514e" }

# Icons
icon_info  = "ïš"
icon_warn  = "ï±"
icon_error = "ï—"

 
[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#e3d18a" },

	# Media
	{ mime = "{audio,video}/*", fg = "#c792ea" },

	# Archives
	{ mime = "application/{,g}zip", fg = "#ff5874" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff5874" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7fdbca" },

	# Empty files
	{ mime = "inode/x-empty", fg = "#fc514e" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ff5874" },
	{ name = "*", is = "exec"  , fg = "green" },

	# Dummy files
	{ name = "*", is = "dummy", bg = "#ff5874" },
	{ name = "*/", is = "dummy", bg = "#ff5874" },

	# Fallback
	{ name = "*", fg = "#d6deeb" },
	{ name = "*/", fg = "#82aaff" }
]


[icon]

globs = [
  { name = "*.txt", text = "ğŸ“ƒ"},
  { name = "*.mom", text = "ğŸ“ƒ"},
  { name = "*.me", text = "ğŸ“ƒ"},
  { name = "*.ms", text = "ğŸ“ƒ"},
  { name = "*.png", text = "ğŸ–¼"},
  { name = "*.webp", text = "ğŸ–¼"},
  { name = "*.ico", text = "ğŸ–¼"},
  { name = "*.jpg", text = "ğŸ“¸"},
  { name = "*.jpe", text = "ğŸ“¸"},
  { name = "*.jpeg", text = "ğŸ“¸"},
  { name = "*.gif", text = "ğŸ–¼"},
  { name = "*.svg", text = "ğŸ—º"},
  { name = "*.tif", text = "ğŸ–¼"},
  { name = "*.tiff", text = "ğŸ–¼"},
  { name = "*.xcf", text = "ğŸ–Œ"},
  { name = "*.html", text = "ğŸŒ"},
  { name = "*.xml", text = "ğŸ“°"},
  { name = "*.gpg", text = "ğŸ”’"},
  { name = "*.css", text = "ğŸ¨"},
  { name = "*.pdf", text = "ğŸ“™"},
  { name = "*.djvu", text = "ğŸ“š"},
  { name = "*.epub", text = "ğŸ“š"},
  { name = "*.csv", text = "ğŸ““"},
  { name = "*.xlsx", text = "ğŸ““"},
  { name = "*.doc", text = "ğŸ“˜"},
  { name = "*.docx", text = "ğŸ“˜"},
  { name = "*.pptx", text = "ğŸ“’"},
  { name = "*.tex", text = "ğŸ“œ"},
  { name = "*.md", text = "ğŸ“—"},
  { name = "*.r", text = "ğŸ“Š"},
  { name = "*.R", text = "ğŸ“Š"},
  { name = "*.rmd", text = "ğŸ“Š"},
  { name = "*.Rmd", text = "ğŸ“Š"},
  { name = "*.m", text = "ğŸ“Š"},
  { name = "*.mp3", text = "ğŸ“»"},
  { name = "*.opus", text = "ğŸ“»"},
  { name = "*.ogg", text = "ğŸ“»"},
  { name = "*.m4a", text = "ğŸ“»"},
  { name = "*.aac", text = "ğŸ“»"},
  { name = "*.flac", text = "ğŸ¼"},
  { name = "*.wav", text = "ğŸ¼"},
  { name = "*.mkv", text = "ğŸ¥"},
  { name = "*.mp4", text = "ğŸ¥"},
  { name = "*.webm", text = "ğŸ¥"},
  { name = "*.mpeg", text = "ğŸ¥"},
  { name = "*.avi", text = "ğŸ¥"},
  { name = "*.mov", text = "ğŸ¥"},
  { name = "*.mpg", text = "ğŸ¥"},
  { name = "*.wmv", text = "ğŸ¥"},
  { name = "*.m4b", text = "ğŸ¥"},
  { name = "*.flv", text = "ğŸ¥"},
  { name = "*.zip", text = "ğŸ“¦"},
  { name = "*.rar", text = "ğŸ“¦"},
  { name = "*.7z", text = "ğŸ“¦"},
  { name = "*.tar.gz", text = "ğŸ“¦"},
  { name = "*.z64", text = "ğŸ®"},
  { name = "*.v64", text = "ğŸ®"},
  { name = "*.n64", text = "ğŸ®"},
  { name = "*.gba", text = "ğŸ®"},
  { name = "*.nes", text = "ğŸ®"},
  { name = "*.gdi", text = "ğŸ®"},
  { name = "*.1", text = "â„¹"},
  { name = "*.nfo", text = "â„¹"},
  { name = "*.info", text = "â„¹"},
  { name = "*.json", text = "ğŸŒµ"},
  { name = "*.log", text = "ğŸ“™"},
  { name = "*.iso", text = "ğŸ“€"},
  { name = "*.img", text = "ğŸ“€"},
  { name = "*.bib", text = "ğŸ“"},
  { name = "*.ged", text = "ğŸ‘ª"},
  { name = "*.part", text = "ğŸ’”"},
  { name = "*.torrent", text = "ğŸ”½"},
  { name = "*.jar", text = "â™¨"},
  { name = "*.java", text = "â™¨"},
  { name = "*.py", text = "ğŸ€"},
  { name = "*.lua", text = "ğŸŒ¸"},
  { name = "*.h", text = "ğŸŒ²"},
  # { name = "*.c", text = "â˜˜"ï¸},
  # { name = "*.cpp", text = "â˜˜"ï¸},
  { name = "*.hpp", text = "ğŸŒ³"},
  # { name = "*.zsh", text = "âš™"ï¸},
  { name = "*.pt", text = "ğŸªµ"},
  { name = "*.pth", text = "ğŸªµ"},
  { name = "*.onnx", text = "ğŸª¨"},
  { name = "*.engine", text = "ğŸ "},
  { name = "*.om", text = "ğŸ "},
  { name = "*.bmodel", text = "ğŸ "},
  { name = "*.bin", text = "ğŸ "},
  { name = "*.param", text = "â„¹"},
  { name = "*.encrypted", text = "ğŸŠ"},
]

dirs  = []
exts = []

conds = [
	# Special files
	# { if = "orphan", text = "ï±" },
	# { if = "link", text = "ï’" },
	# { if = "block", text = "ïƒ‰" },
	# { if = "char", text = "ï‡€" },
	# { if = "fifo", text = "ï‡‘" },
	# { if = "sock", text = "ï‡¤" },
	# { if = "sticky", text = "ï‡¼" },
	# { if = "dummy", text = "ï—" },

	{ if = "link", text = "â›“" },

	{ if = "orphan", text = "âŒ" },

  { if = "hidden & dir", text = "ğŸ‘»" },
	{ if = "dir", text = "ğŸ“" },
	{ if = "!dir & exec", text = "ğŸ¯" },
	{ if = "!(dir | link)", text = "ğŸ“ƒ" },

  ]
