[manager]
marker_copied   = { fg = "#98bb6c", bg = "#98bb6c" } # green
marker_cut      = { fg = "#e46876", bg = "#e46876" } # red
marker_marked   = { fg = "#957fb8", bg = "#957fb8" } # magenta
marker_selected = { fg = "#ffa066", bg = "#ffa066" } # cyan

cwd = { fg = "#e6c384" } # yellow
hovered = { reversed = true }
preview_hovered = { reversed = true }

tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# default bg
count_copied   = { fg = "#1f1f28", bg = "#98bb6c" } # green
count_cut      = { fg = "#1f1f28", bg = "#e46876" } # red
count_selected = { fg = "#1f1f28", bg = "#e6c384" } # yellow

border_symbol = "â”‚"
border_style = { fg = "#dcd7ba"} # white

# status-line
[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "reset", bg = "#363646" } # light bg

# default bg
mode_normal = { fg = "#1f1f28", bg = "#85a6ea", bold = true } # blue
mode_select = { fg = "#1f1f28", bg = "#957fb8", bold = true } # magenta
mode_unset  = { fg = "#1f1f28", bg = "#e6c384", bold = true } # yellow

# blue - light bg
progress_label  = { fg = "#85a6ea", bg = "#363646", bold = true }
# light bg - default bg
progress_normal = { fg = "#363646", bg = "#1f1f28" }
progress_error  = { fg = "#363646", bg = "#1f1f28" }

permissions_t = { fg = "#98bb6c" } # green
permissions_r = { fg = "#e6c384" } # yellow
permissions_w = { fg = "#e82424" } # red
permissions_x = { fg = "#7aa89f" } # cyan
permissions_s = { fg = "#938aa9" } # magenta

[select]
border   = { fg = "#7fb4ca" } # blue
active   = { fg = "#938aa9", bold = true } # magenta
inactive = {}

[input]
border   = { fg = "#7fb4ca" } # blue
title    = {}
value    = {}
selected = { reversed = true }

[cmp]
border   = { fg = "#7fb4ca" } # blue
active   = { reversed = true }
inactive = {}

[tasks]
border  = { fg = "#7fb4ca" } # blue
title   = {}
hovered = { fg = "#938aa9" } # magenta

[which]
cols = 2
separator = " - "
separator_style = { fg = "#727169" } # darkgrey
mask = { bg = "#16161d" } # dark bg
rest = { fg = "#727169" } # darkgrey
cand = { fg = "#85a6ea" }
desc = { fg = "#565666" }

[help]
on      = { fg = "#7aa89f" } # cyan
run     = { fg = "#938aa9" } # magenta
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#090618", bg = "#dcd7ba" } # white

[notify]
title_info  = { fg = "#98bb6c" } # green
title_warn  = { fg = "#e6c384" } # yellow
title_error = { fg = "#e82424" } # red

# files
[filetype]
rules = [
    { mime = "image/*", fg = "#e6c384" },
    { mime = "{audio,video}/*", fg = "#957fb8" },
    { mime = "application/{,g}zip", fg = "#e46876" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e46876" },
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#6a9589" },
    { name = "*", is = "orphan", fg = "#e46876" },
    { name = "*", is = "exec", fg = "#957fb8" },
    { name = "*/", fg = "#85a6ea"}
]


[icon]

globs = [
  { name = "*.txt", text = "ğŸ“ƒ"},
  { name = "*.mom", text = "ğŸ“ƒ"},
  { name = "*.me", text = "ğŸ“ƒ"},
  { name = "*.ms", text = "ğŸ“ƒ"},
  { name = "*.png", text = "ğŸ–¼"},
  { name = "*.webp", text = "ğŸ–¼"},
  { name = "*.ico", text = "ğŸ–¼"},
  { name = "*.jpg", text = "ğŸ“¸"},
  { name = "*.jpe", text = "ğŸ“¸"},
  { name = "*.jpeg", text = "ğŸ“¸"},
  { name = "*.gif", text = "ğŸ–¼"},
  { name = "*.svg", text = "ğŸ—º"},
  { name = "*.tif", text = "ğŸ–¼"},
  { name = "*.tiff", text = "ğŸ–¼"},
  { name = "*.xcf", text = "ğŸ–Œ"},
  { name = "*.html", text = "ğŸŒ"},
  { name = "*.xml", text = "ğŸ“°"},
  { name = "*.gpg", text = "ğŸ”’"},
  { name = "*.css", text = "ğŸ¨"},
  { name = "*.pdf", text = "ğŸ“™"},
  { name = "*.djvu", text = "ğŸ“š"},
  { name = "*.epub", text = "ğŸ“š"},
  { name = "*.csv", text = "ğŸ““"},
  { name = "*.xlsx", text = "ğŸ““"},
  { name = "*.doc", text = "ğŸ“˜"},
  { name = "*.docx", text = "ğŸ“˜"},
  { name = "*.pptx", text = "ğŸ“’"},
  { name = "*.tex", text = "ğŸ“œ"},
  { name = "*.md", text = "ğŸ“—"},
  { name = "*.r", text = "ğŸ“Š"},
  { name = "*.R", text = "ğŸ“Š"},
  { name = "*.rmd", text = "ğŸ“Š"},
  { name = "*.Rmd", text = "ğŸ“Š"},
  { name = "*.m", text = "ğŸ“Š"},
  { name = "*.mp3", text = "ğŸ“»"},
  { name = "*.opus", text = "ğŸ“»"},
  { name = "*.ogg", text = "ğŸ“»"},
  { name = "*.m4a", text = "ğŸ“»"},
  { name = "*.aac", text = "ğŸ“»"},
  { name = "*.flac", text = "ğŸ¼"},
  { name = "*.wav", text = "ğŸ¼"},
  { name = "*.mkv", text = "ğŸ¥"},
  { name = "*.mp4", text = "ğŸ¥"},
  { name = "*.webm", text = "ğŸ¥"},
  { name = "*.mpeg", text = "ğŸ¥"},
  { name = "*.avi", text = "ğŸ¥"},
  { name = "*.mov", text = "ğŸ¥"},
  { name = "*.mpg", text = "ğŸ¥"},
  { name = "*.wmv", text = "ğŸ¥"},
  { name = "*.m4b", text = "ğŸ¥"},
  { name = "*.flv", text = "ğŸ¥"},
  { name = "*.zip", text = "ğŸ“¦"},
  { name = "*.rar", text = "ğŸ“¦"},
  { name = "*.7z", text = "ğŸ“¦"},
  { name = "*.tar.gz", text = "ğŸ“¦"},
  { name = "*.z64", text = "ğŸ®"},
  { name = "*.v64", text = "ğŸ®"},
  { name = "*.n64", text = "ğŸ®"},
  { name = "*.gba", text = "ğŸ®"},
  { name = "*.nes", text = "ğŸ®"},
  { name = "*.gdi", text = "ğŸ®"},
  { name = "*.1", text = "â„¹"},
  { name = "*.nfo", text = "â„¹"},
  { name = "*.info", text = "â„¹"},
  { name = "*.json", text = "ğŸŒµ"},
  { name = "*.log", text = "ğŸ“™"},
  { name = "*.iso", text = "ğŸ“€"},
  { name = "*.img", text = "ğŸ“€"},
  { name = "*.bib", text = "ğŸ“"},
  { name = "*.ged", text = "ğŸ‘ª"},
  { name = "*.part", text = "ğŸ’”"},
  { name = "*.torrent", text = "ğŸ”½"},
  { name = "*.jar", text = "â™¨"},
  { name = "*.java", text = "â™¨"},
  { name = "*.py", text = "ğŸ€"},
  { name = "*.lua", text = "ğŸŒ¸"},
  { name = "*.h", text = "ğŸŒ²"},
  # { name = "*.c", text = "â˜˜"ï¸},
  # { name = "*.cpp", text = "â˜˜"ï¸},
  { name = "*.hpp", text = "ğŸŒ³"},
  # { name = "*.zsh", text = "âš™"ï¸},
  { name = "*.pt", text = "ğŸªµ"},
  { name = "*.pth", text = "ğŸªµ"},
  { name = "*.onnx", text = "ğŸª¨"},
  { name = "*.engine", text = "ğŸ "},
  { name = "*.om", text = "ğŸ "},
  { name = "*.bmodel", text = "ğŸ "},
  { name = "*.bin", text = "ğŸ "},
  { name = "*.param", text = "â„¹"},
  { name = "*.encrypted", text = "ğŸŠ"},
]

dirs  = []
exts = []

conds = [
	# Special files
	# { if = "orphan", text = "ï±" },
	# { if = "link", text = "ï’" },
	# { if = "block", text = "ïƒ‰" },
	# { if = "char", text = "ï‡€" },
	# { if = "fifo", text = "ï‡‘" },
	# { if = "sock", text = "ï‡¤" },
	# { if = "sticky", text = "ï‡¼" },
	# { if = "dummy", text = "ï—" },

	{ if = "link", text = "â›“" },

	{ if = "orphan", text = "âŒ" },

  { if = "hidden & dir", text = "ğŸ‘»" },
	{ if = "dir", text = "ğŸ“" },
	{ if = "!dir & exec", text = "ğŸ¯" },
	{ if = "!(dir | link)", text = "ğŸ“ƒ" },

  ]
